# schemas/itinerary.py
from pydantic import BaseModel, Field, field_validator
from typing import List, Optional, Dict, Any, Literal

# Aligned EXACTLY with ACTIVITY_STYLES / ACTIVITY_ICON_PATHS in
# components/itinerary/icons.jsx and TimelineItem.jsx. If you add a type
# here, add a matching icon + style on the frontend (or it silently falls
# back to the generic pin/style there).
ActivityType = Literal[
    "food", "sightseeing", "hotel", "travel", "shopping", "nature",
    "adventure", "culture", "relaxation", "photography", "beach", "arrival",
]


class Meal(BaseModel):
    meal_type: Literal["breakfast", "lunch", "dinner", "snack", "none"] = "none"
    cuisine_type: Optional[str] = None
    dining_style: Optional[str] = None
    veg_friendly: Optional[bool] = None


class ActivityBlock(BaseModel):
    """One activity in a day. No more fixed 'period' field — order within
    the day's `blocks` list plus `time_window` conveys sequence, matching
    how DayCard/TimelineItem actually consume this (they never read a
    'period' field)."""
    id: Optional[str] = None
    time_window: Optional[str] = None
    activity_type: Optional[ActivityType] = None
    title: str
    description: Optional[str] = None
    location: Optional[str] = None
    estimated_duration: Optional[str] = None
    estimated_cost: Optional[str] = None
    meal: Meal = Field(default_factory=Meal)
    logistics_hint: Optional[str] = None
    photography_note: Optional[str] = None
    important_tip: Optional[str] = None
    optional_label: Optional[str] = None

    @field_validator("meal", mode="before")
    @classmethod
    def ensure_meal_not_none(cls, v):
        if v is None:
            return Meal()
        return v


class DayPlan(BaseModel):
    day: int
    day_theme: Optional[str] = None
    day_summary: Optional[str] = None
    highlights: Optional[List[str]] = None
    blocks: List[ActivityBlock] = Field(default_factory=list)


class OverallStyle(BaseModel):
    """Filled in by the server from `constraints`, not generated by the AI —
    it's just an echo of what the user/Module 5 already specified."""
    pace: Optional[str] = None
    budget: Optional[str] = None
    experience_style: Optional[str] = None
    comfort_level: Optional[str] = None


class TripStats(BaseModel):
    """Computed server-side after generation (distance from trip_summary,
    places_covered by counting blocks, budget display formatted from
    budget_breakdown) — never asked of the AI, to avoid hallucinated numbers."""
    distance_km: Optional[float] = None
    places_covered: Optional[int] = None
    estimated_budget_display: Optional[str] = None


class WeatherInfo(BaseModel):
    icon: Optional[str] = None
    temp_min: Optional[float] = None
    temp_max: Optional[float] = None
    summary: Optional[str] = None
    best_time_to_visit: Optional[str] = None


class BudgetBreakdown(BaseModel):
    total: Optional[float] = None
    accommodation: Optional[float] = None
    food: Optional[float] = None
    transportation: Optional[float] = None
    entry_tickets: Optional[float] = None
    shopping: Optional[float] = None
    miscellaneous: Optional[float] = None


class PlaceItem(BaseModel):
    name: str
    description: Optional[str] = None
    category: Optional[str] = None


class FoodItem(BaseModel):
    name: str
    description: Optional[str] = None


class RestaurantItem(BaseModel):
    name: str
    description: Optional[str] = None
    cuisine: Optional[str] = None
    price_range: Optional[str] = None
    location: Optional[str] = None


class EssentialInfo(BaseModel):
    emergency_number: Optional[str] = None
    hospital: Optional[str] = None
    police: Optional[str] = None
    tourist_helpline: Optional[str] = None
    transport_info: Optional[str] = None
    atm_availability: Optional[str] = None
    mobile_network: Optional[str] = None


class ItineraryResponse(BaseModel):
    # --- Set deterministically by the server from trip_summary/constraints,
    # never generated by the AI (see routes/itinerary_route.py) ---
    destination: str
    source: Optional[str] = None
    days: int
    travel_mode: Optional[str] = None
    group_type: Optional[str] = None
    overall_style: OverallStyle = Field(default_factory=OverallStyle)
    trip_stats: TripStats = Field(default_factory=TripStats)

    # --- Generated by the AI ---
    weather: Optional[WeatherInfo] = None
    budget_breakdown: Optional[BudgetBreakdown] = None
    transportation_advice: Optional[List[str]] = None
    packing_list: Optional[List[str]] = None
    must_visit_places: Optional[List[PlaceItem]] = None
    hidden_gems: Optional[List[PlaceItem]] = None
    local_food: Optional[List[FoodItem]] = None
    restaurant_recommendations: Optional[List[RestaurantItem]] = None
    shopping_suggestions: Optional[List[str]] = None
    photography_tips: Optional[List[str]] = None
    travel_tips: Optional[List[str]] = None
    essential_information: Optional[EssentialInfo] = None
    emergency_contacts: Optional[Dict[str, str]] = None
    itinerary: List[DayPlan]

    # --- Catch-all so an unexpected AI key is never silently dropped ---
    additional_information: Optional[Dict[str, Any]] = Field(default_factory=dict)

    @field_validator("itinerary")
    @classmethod
    def each_day_has_blocks(cls, itinerary: List[DayPlan]) -> List[DayPlan]:
        for day in itinerary:
            if not day.blocks:
                raise ValueError(f"Day {day.day} has no activity blocks")
        return itinerary